use std::fmt;

use secrecy::{ExposeSecret, SecretBox, SecretString};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use thiserror::Error;

/// Bytes of a [`Selector`]: enough to make collisions between live tokens
/// irrelevant, never enough to authenticate anything.
pub const SELECTOR_BYTES: usize = 16;

/// Bytes of a [`Verifier`]: 256 bits from the OS CSPRNG -- beyond guessing,
/// which is why its stored hash is SHA-256 and not Argon2 (see
/// [`VerifierHash`]).
pub const VERIFIER_BYTES: usize = 32;

/// The one bearer-secret shape this module issues: session cookies, reset
/// links and invitation links are all a `SplitToken`.
///
/// Two halves, with different jobs:
///
/// - the **selector** finds the row. It is stored in clear under a unique
///   index, so lookup is an ordinary indexed query;
/// - the **verifier** proves possession. Only `SHA-256(verifier)` is stored,
///   and a presented verifier is checked against it in constant time, in
///   Rust, by [`VerifierHash::verifies`].
///
/// Why not one token hashed and looked up with `WHERE hash = $1`: the index
/// comparison is not constant-time. Hashing already makes that harmless -- a
/// prefix match on `SHA-256(x)` says nothing about `x` -- but the split puts
/// the constant-time comparison where it can be read and tested, rather
/// than leaving it to an argument about B-trees.
///
/// A leaked copy of the tables holds selectors and verifier hashes: enough
/// to find a row, not enough to present a token that verifies.
///
/// Wire form: `hex(selector) "." hex(verifier)`, 32 + 1 + 64 characters.
/// This type does not generate its bytes; an OS-backed generator lives in
/// the service crate, so this crate makes no system calls.
pub struct SplitToken {
    selector: Selector,
    verifier: Verifier,
}

impl SplitToken {
    /// Builds a token from freshly generated bytes.
    pub fn from_bytes(selector: [u8; SELECTOR_BYTES], verifier: [u8; VERIFIER_BYTES]) -> Self {
        Self {
            selector: Selector(selector),
            verifier: Verifier(SecretBox::new(Box::new(verifier))),
        }
    }

    /// Parses the wire form. Every malformation -- wrong length, missing
    /// separator, non-hex -- is the same [`TokenParseError`]: a caller
    /// probing the format learns nothing about which part it got wrong.
    pub fn parse(wire: &str) -> Result<Self, TokenParseError> {
        let (selector_hex, verifier_hex) = wire.split_once('.').ok_or(TokenParseError)?;
        let mut selector = [0u8; SELECTOR_BYTES];
        hex::decode_to_slice(selector_hex, &mut selector).map_err(|_| TokenParseError)?;
        let mut verifier = [0u8; VERIFIER_BYTES];
        hex::decode_to_slice(verifier_hex, &mut verifier).map_err(|_| TokenParseError)?;
        Ok(Self::from_bytes(selector, verifier))
    }

    /// The wire form. Returned as a secret: it is the whole credential.
    pub fn to_wire(&self) -> SecretString {
        let wire = format!(
            "{}.{}",
            hex::encode(self.selector.0),
            hex::encode(self.verifier.0.expose_secret())
        );
        SecretString::from(wire)
    }

    /// The half that finds the row.
    pub fn selector(&self) -> Selector {
        self.selector
    }

    /// The half that proves possession.
    pub fn verifier(&self) -> &Verifier {
        &self.verifier
    }
}

impl fmt::Debug for SplitToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("SplitToken")
            .field("selector", &self.selector)
            .field("verifier", &self.verifier)
            .finish()
    }
}

/// The lookup half of a [`SplitToken`]. Not secret on its own -- it is stored
/// in clear -- so its `Debug` shows it, which makes a session findable from a
/// log line without making it usable.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct Selector([u8; SELECTOR_BYTES]);

impl Selector {
    /// Wraps stored bytes.
    pub fn from_bytes(bytes: [u8; SELECTOR_BYTES]) -> Self {
        Self(bytes)
    }

    /// The bytes, for binding to a query.
    pub fn as_bytes(&self) -> &[u8; SELECTOR_BYTES] {
        &self.0
    }
}

impl fmt::Debug for Selector {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Selector({})", hex::encode(self.0))
    }
}

/// The secret half of a [`SplitToken`]. Never stored, never logged: its
/// `Debug` is redacted and the bytes are zeroed on drop (`SecretBox`).
pub struct Verifier(SecretBox<[u8; VERIFIER_BYTES]>);

impl Verifier {
    /// `SHA-256(verifier)` -- the only form of it that is ever stored.
    pub fn hash(&self) -> VerifierHash {
        VerifierHash(Sha256::digest(self.0.expose_secret()).into())
    }
}

impl fmt::Debug for Verifier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Verifier([REDACTED])")
    }
}

/// `SHA-256(verifier)`, as stored.
///
/// SHA-256 and not Argon2, deliberately. Argon2 exists to make guessing a
/// *low-entropy* secret expensive; a 256-bit random verifier cannot be
/// guessed at any cost, so a slow hash would buy nothing -- and it runs on
/// every authenticated request, where tens of milliseconds each is a
/// denial-of-service lever. Passwords, which humans choose, get Argon2id.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct VerifierHash([u8; VERIFIER_BYTES]);

impl VerifierHash {
    /// Wraps stored bytes.
    pub fn from_bytes(bytes: [u8; VERIFIER_BYTES]) -> Self {
        Self(bytes)
    }

    /// The bytes, for binding to a query.
    pub fn as_bytes(&self) -> &[u8; VERIFIER_BYTES] {
        &self.0
    }

    /// Whether `presented` hashes to this value, compared in constant time.
    ///
    /// The comparison is over the two 32-byte hashes with
    /// `subtle::ConstantTimeEq`, which examines every byte whatever the
    /// first mismatch -- an early-exit `==` here would leak, through
    /// timing, how many leading bytes matched. Both operands are always
    /// exactly 32 bytes, so length is not a side channel either.
    pub fn verifies(&self, presented: &Verifier) -> bool {
        let presented = presented.hash();
        presented.0.ct_eq(&self.0).into()
    }
}

impl fmt::Debug for VerifierHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("VerifierHash(..)")
    }
}

/// A presented token was not in the wire form. Deliberately detail-free.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[error("malformed token")]
pub struct TokenParseError;

#[cfg(test)]
mod tests {
    use super::*;

    const SELECTOR: [u8; SELECTOR_BYTES] = [0x11; SELECTOR_BYTES];
    const VERIFIER: [u8; VERIFIER_BYTES] = [0x22; VERIFIER_BYTES];

    fn token() -> SplitToken {
        SplitToken::from_bytes(SELECTOR, VERIFIER)
    }

    #[test]
    fn wire_form_round_trips_exactly() {
        let wire = token().to_wire();
        let parsed = SplitToken::parse(wire.expose_secret());

        assert!(matches!(&parsed, Ok(t) if t.selector() == Selector(SELECTOR)));
        assert_eq!(
            parsed.map(|t| t.to_wire().expose_secret().to_string()),
            Ok(wire.expose_secret().to_string())
        );
        assert_eq!(wire.expose_secret().len(), 32 + 1 + 64);
    }

    #[test]
    fn every_malformation_is_the_same_error() {
        let good = token().to_wire().expose_secret().to_string();
        let (selector, verifier) = good.split_at(32);
        let verifier = &verifier[1..];

        for wire in [
            String::new(),
            good.replace('.', ""),
            selector.to_string(),
            format!("{selector}.{}", &verifier[1..]),
            format!("{}.{verifier}", &selector[1..]),
            format!("{selector}.{verifier}00"),
            format!("{selector}.{}zz", &verifier[2..]),
            format!("{selector}.{verifier}.{verifier}"),
        ] {
            assert_eq!(
                SplitToken::parse(&wire).err(),
                Some(TokenParseError),
                "{wire:?}"
            );
        }
    }

    /// R6 -- the reset token (and every other token) is compared in
    /// constant time.
    ///
    /// **This test does not measure timing**, and does not pretend to: a
    /// timing assertion in a unit test is either flaky or meaningless. What
    /// it pins is the behaviour of the one comparison the module has --
    /// that `verifies` accepts the right verifier and rejects equal-length
    /// wrong ones, including one differing only in its last byte and one
    /// differing only in its first -- while the constant-time property
    /// itself rests on `VerifierHash::verifies` delegating to
    /// `subtle::ConstantTimeEq`, which a reader checks in one line.
    #[test]
    fn verification_uses_constant_time_equality() {
        let stored = token().verifier().hash();

        assert!(stored.verifies(token().verifier()));

        let mut last_differs = VERIFIER;
        last_differs[VERIFIER_BYTES - 1] ^= 1;
        let mut first_differs = VERIFIER;
        first_differs[0] ^= 1;

        for wrong in [last_differs, first_differs, [0u8; VERIFIER_BYTES]] {
            let presented = SplitToken::from_bytes(SELECTOR, wrong);
            assert!(!stored.verifies(presented.verifier()));
        }
    }

    #[test]
    fn the_stored_hash_is_not_the_verifier() {
        let stored = token().verifier().hash();
        assert_ne!(stored.as_bytes(), &VERIFIER);
    }

    #[test]
    fn debug_never_prints_the_verifier() {
        let rendered = format!("{:?}", token());
        assert!(!rendered.contains(&hex::encode(VERIFIER)));
        assert!(!rendered.contains(&hex::encode(token().verifier().hash().as_bytes())));
        // The selector is not secret and is shown, so a row can be found
        // from a log line.
        assert!(rendered.contains(&hex::encode(SELECTOR)));
    }
}
